netpanzer/netpanzer

- SConstruct
Fixes project not building on recent operating systems which have switched to Python 3.
> Build Issues: Migrate SConstruct To Python 3

- SConstruct
- src/Lib/2D/ColorTable.cpp
- src/Lib/2D/PackedSurface.cpp
- src/Lib/2D/Palette.cpp
- src/Lib/2D/Surface.cpp
- src/Lib/Network/Address.cpp
- src/Lib/Network/Address.hpp
- src/Lib/Network/SocketBase.cpp
- src/Lib/Network/SocketBase.hpp
- src/Lib/Network/TCPSocket.cpp
- src/Lib/Network/TCPSocket.hpp
- src/Lib/Network/UDPSocket.cpp
- src/Lib/Network/UDPSocket.hpp
- src/NetPanzer/Classes/TileSet.cpp
- src/NetPanzer/Classes/TipOfDay.cpp
- src/NetPanzer/Classes/WorldMap.cpp
- src/NetPanzer/Views/MainMenu/Multi/MapSelectionView.cpp
1. Now successfully compiles with -std=c++17 and g++11
2. c++17 removes "dynamic exception declarations". This is an easy fix.
3. c++17 deprecates auto_ptr and introduces unique_ptr and shared_ptr. We should switch to unique_ptr here.
> Build Issues: Fixes Some Build Errors and Warnings For C++17

- src/NetPanzer/Core/main.cpp
Fixes:
```
ERROR: Couldn't initialize SDL: No available video device
```
> Fix dedicated servers after SDL2 migration

- src/NetPanzer/Core/main.cpp
- src/NetPanzer/Interfaces/BaseGameManager.cpp
- src/NetPanzer/Interfaces/GameConfig.cpp
Sometimes when the server crashes, it could overwrite the config file with a whole new one. This was due to calling `saveConfig()` in various places on shutdown and also in the `GameConfig` deconstructor, which could be called if something failed during startup and the config is not fully read.
This fixes things so `saveConfig()` is only called on a successful shutdown.
> Server should not overwrite config on error with potentially incorrect or invalid state.

- .github/workflows/c-cpp.yml
Trying to fix the clang build in the CI
> c-cpp.yml: remove unneeded install of compilers

- src/NetPanzer/Views/Game/RankView.cpp
Fixes the multiple definition errors I mentioned in https://github.com/netpanzer/netpanzer/pull/46
> Views/Game/RankView.cpp: include header, not cpp source

- src/NetPanzer/Views/Components/cInputField.cpp
fixes #65
According to the memcpy man page
>The  memcpy()  function copies n bytes from memory area src to memory area dest.  The memory areas must not over‐lap.  Use memmove(3) if the memory areas do overlap.
I don't know how much testing this needs. I pressed the del key and it worked as expected.
I also tested with the backspace key. Same problem. Now fixed, as far as I can tell.
> cInputField.cpp: Fix memory overlap in Name Input field

- src/NetPanzer/Views/Components/cInputField.cpp
This should have been part of #65
> cInputField.cpp: Fix backspace when editing Name

- src/Lib/2D/CachedFontRenderer.cpp
- src/Lib/2D/CachedFontRenderer.hpp
- src/Lib/2D/Surface.cpp
- src/Lib/2D/Surface.hpp
- src/NetPanzer/Interfaces/PlayerGameManager.cpp
- src/NetPanzer/meson.build
Addresses #10 
This puts the font rendering in a pool of surfaces, cached by text and color. This is an optimization to prevent random allocations per-frame. It periodically garbage collects, on a safe interval to prevent memory leaks. Based on testing this does not cause any dropped frames with the current number of rendered fonts.
> Cache Rendered Fonts

- meson.build
We might consider leaving this as the default for a while. It might help us catch existing bugs or prevent introducing new ones.
It can be turned off by using 'meson configure -Db_sanitize=none -Db_lundef=true' from the build directory.
I'm not too sure what the l_undef does, but meson warns about some potential clang compatibility when using b_sanitize=address,undefined with lundef set to true (the default).
> meson: Enable sanitize

- src/NetPanzer/Classes/WorldInputCmdProcessor.cpp
- src/NetPanzer/Interfaces/MouseInterface.hpp
- src/NetPanzer/System/SDLVideo.cpp
Fixes #74 
1. Map movement via mouse on edge of window no longer jerky.
2. Mouse doesn't go beyond black bars.
3. Mouse doesn't go onto 2nd monitor in fullscreen mode.
4. Mouse can leave windowed mode but you can use edge of map movement.
> Mouse Movement Fixes (Jerky Movement etc)

- src/Lib/2D/CachedFontRenderer.cpp
Technically direct cast to char* from w_char* is not correct, but unblocks build for now. Changed type from filesystem::path to string... hopefully nobody puts super fancy characters in file system paths :) netpanzer does not support it.
Error:
```
src\\Lib\\2D\\CachedFontRenderer.cpp: In static member function \'static void CachedFontRenderer::initFont()\':\nsrc\\Lib\\2D\\CachedFontRenderer.cpp:43:37: error: cannot convert \'con
st std::filesystem::__cxx11::path::value_type*\' {aka \'const wchar_t*\'} to \'const char*\'\n   43 |       TTF_OpenFont(absFontPath.c_str(), FONT_SIZE);\n      |                    ~~~~
~~~~~~~~~~~~~^~\n      |                                     |\n      |                                     const std::filesystem::__cxx11::path::value_type* {aka const …
```
> Fixes Not Compiling on Windows

- meson.build
Right now when it's enabled, NP crashes before it gets to the main menu. I think we should disable it until the game can actually be played.
> meson: temporarily disable sanitize

- README.md
We shouldn't link to GitHub when the file is in the current directory structure. The links will still be rendered properly on GH. Helps with editor integration.
> Use Relative Paths in README

- src/NetPanzer/Particles/ParticleInterface.cpp
Seems to fix it. Got crash before, don't now. Don't know flow well enough yet to why the vector is empty here but it crashes randomly due to the rand() further up in this method, I think.
> Fixes Random Crash

- src/NetPanzer/Particles/ParticleInterface.cpp
- src/NetPanzer/System/SDLSound.cpp
- src/NetPanzer/System/Sound.cpp
- src/NetPanzer/Weapons/Weapon.cpp
- Now everything on the map is not 100% volume all the time (very annoying w/ large matches).
- Fixes playAmbientSound() not respecting distance parameter.
- Adjusted distances some based on what feels nice.
- Users can still look at mini map to see if they're being attacked etc.
> Adding Proximity Audio For Hits and Explosions, Fixes Variable Audio Broken

- support/win32/netpanzer.desktop
I used a Debian patch
The Encoding field is deprecated if I'm not mistaken.
Fixes #172
> maint: Patch netpanzer.desktop

- .cirrus.yml
Changed by
https://github.com/netpanzer/netpanzer/commit/d527e1293af5d6043ceaf14266d908aa82919b00
> CI: Update image:tag for arm64 container in cirrus

- meson.build
These are required by SDL2_mixer. If it's not found, it will use the ogg and vorbis wraps in the subprojects directory.
> meson: Remove ogg and vorbis

- meson.build
I thought meson didn't allow this but I was wrong.
> meson: Use alpha chars in version number

- src/NetPanzer/Views/Game/UStyleSelectionView.cpp
Fixes [https://github.com/netpanzer/netpanzer/security/code-scanning/9](https://github.com/netpanzer/netpanzer/security/code-scanning/9)
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert #9: Comparison of narrow type with wide type in loop condition

- src/Lib/2D/Surface.hpp
Fixes [https://github.com/netpanzer/netpanzer/security/code-scanning/35](https://github.com/netpanzer/netpanzer/security/code-scanning/35)
To fix the problem, we need to ensure that the multiplication is performed using the larger type `size_t` to prevent overflow. This can be achieved by casting one of the operands to `size_t` before performing the multiplication. This way, the multiplication will be done in the larger type, and the result will be correctly assigned to the `size_t` variable `frame_len`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 35: Multiplication result converted to larger type

- src/Lib/ArrayUtil/BitArray.cpp
Fixes https://github.com/netpanzer/netpanzer/issues/250
It would be good to know *how* these out of bounds values could be created. AFAIK they are created like this:
```
map_size_x = MapInterface::getWidth();
map_size_y = MapInterface::getHeight();
loc.x = rand() % map_size_x;
loc.y = rand() % map_size_y;
if (MapInterface::getMovementValue(loc) == 0xFF) {
```
> Adding Bounds Check for Heap Buffer Overflow

- src/Lib/Util/Log.cpp
- src/NetPanzer/Interfaces/BaseGameManager.cpp
- src/NetPanzer/Interfaces/BotGameManager.cpp
- src/NetPanzer/Interfaces/DedicatedGameManager.cpp
- src/NetPanzer/Interfaces/GameConfig.cpp
- src/NetPanzer/Interfaces/GameConfig.hpp
- src/NetPanzer/Interfaces/MenuConfig.cpp
- src/NetPanzer/Scripts/ScriptManager.cpp
- src/NetPanzer/Scripts/ScriptManager.hpp
Fixes https://github.com/netpanzer/netpanzer/issues/264
I think differentiating between using physfs or not is a bad idea. We should just always use paths relative to physfs.
Also fixes default log level to be INFO, I have always wondered why info logs don't work :)
> Fixes Bots Crashing - Always use physfs
