netpanzer/netpanzer

- src/NetPanzer/Classes/SelectionBoxSprite.cpp
- src/NetPanzer/Interfaces/ConsoleInterface.cpp
> Fixing Flag Alignment Bugs

- src/NetPanzer/Interfaces/GameManager.cpp
- src/NetPanzer/Network/ClientSocket.cpp
Tested with 20 clicks a second.
> Fixes Anti Cheat Not Working

- src/NetPanzer/System/SDLVideo.cpp
Fixes a lot of bugs! Feels much smoother now, too. We no longer re-create the window for every change.
> Rewrite Resolution/Fullscreen Switching

- src/NetPanzer/Views/MainMenu/CreditsScrollView.cpp
> CreditsScrollView.cpp: conditionally include config.h

- src/NetPanzer/System/SDLSound.cpp
Not that anyone is using netpanzer to play music in 2024 :)
> Removing use of random_shuffle (deprecated)

- .github/dependabot.yml
- .github/workflows/c-cpp.yml
This will cause dependabot to open a PR if it finds that some actions have been updated
> CI: add dependabot

- src/NetPanzer/Interfaces/MapInterface.cpp
> MapInterface: Fix undefined behavior when using memcpy

- src/NetPanzer/Core/main.cpp
- src/NetPanzer/Interfaces/BaseGameManager.cpp
- src/NetPanzer/Interfaces/BaseGameManager.hpp
- src/NetPanzer/Interfaces/GameConfig.cpp
Verified:
```
$ ls ~/.netpanzer/config/
$ ./netpanzer 
initialize game config
rendering text Please wait... generating palettes
2024-01-09 10:31:16 Config saved.
$ ls ~/.netpanzer/config/
client.cfg
```
> Fix Game Config Not Saving

- src/Lib/optionmm/command_line.hpp
Maybe help with the macos build?
> macos: fix build

- SConstruct
This is a Debian patch that's named 'reproducible-build.patch'
https://packages.debian.org/bookworm/netpanzer
> scons: apply Debian patch for repro build

- src/Lib/Util/BresenhamLine.cpp
- src/Lib/Util/BresenhamLine.hpp
- src/Lib/Util/Endian.hpp
- src/Lib/Util/Exception.cpp
- src/Lib/Util/Exception.hpp
- src/Lib/Util/FileStream.hpp
- src/Lib/Util/FileSystem.cpp
- src/Lib/Util/FileSystem.hpp
- src/Lib/Util/Log.cpp
- src/Lib/Util/Log.hpp
- src/Lib/Util/Math.cpp
- src/Lib/Util/Math.hpp
- src/Lib/Util/NTimer.hpp
- src/Lib/Util/NoCopy.hpp
- src/Lib/Util/StreamTokenizer.hpp
- src/Lib/Util/StringTokenizer.hpp
- src/Lib/Util/StringUtil.cpp
- src/Lib/Util/StringUtil.hpp
- src/Lib/Util/TimeStamp.cpp
- src/Lib/Util/TimeStamp.hpp
- src/Lib/Util/Timer.cpp
- src/Lib/Util/Timer.hpp
- src/Lib/Util/TimerInterface.cpp
- src/Lib/Util/TimerInterface.hpp
- src/Lib/Util/UtilInterface.cpp
- src/Lib/Util/UtilInterface.hpp
Just trying out clang-format ;) The command I used was:
find . -iname \*.hpp -o -iname \*.cpp | xargs clang-format -i
https://stackoverflow.com/questions/28896909/how-to-call-clang-format-over-a-cpp-project-folder
> maint: Reformat Lib/Util

- src/NetPanzer/System/SDLVideo.cpp
- src/NetPanzer/System/SDLVideo.hpp
> Improving fullscreen switch reliability

- src/NetPanzer/Classes/WorldInputCmdProcessor.cpp
- src/NetPanzer/System/SDLVideo.cpp
- src/NetPanzer/System/SDLVideo.hpp
Fixes #75
Now has "smooth" scrolling on right click.
Still could use some improvements, but is at least usable now.
> Fixes mouse zooming to top left

- src/NetPanzer/Views/MainMenu/CreditsScrollView.cpp
@winrid This segfaults when I hit the 'Credits' tab. Any idea why? I'm passing a const char* like the insert function wants...
> refactor Credits (closes #99)

- tests/meson.build
> tests: don't link to all deps

- support/release-checklist.txt
- support/scripts/make-appimage.sh
- support/scripts/prep-appimage.sh
> docs: Add release-checklist.txt and minor update appimage scripts

- src/Lib/2D/CachedFontRenderer.cpp
> bugfix: Prepend dataDir when opening font

- README.md
> docs: Add meson instructions

- CONTRIBUTING.md
- README.md
> docs: Add contact section to README

- .github/workflows/check-formatting.yml
Related to #43
Code courtesy of ChatGPT and lightly modified by me.
> CI: Check code formatting

- src/NetPanzer/Interfaces/GameControlRulesDaemon.cpp
- src/NetPanzer/Interfaces/GameControlRulesDaemon.hpp
- src/NetPanzer/Interfaces/InfoSocket.cpp
Fixes #89 
Tested on my own server in server list.
> Use server.name config for dedicated servers

- README.md
- docs/SERVER-HOWTO.md
> docs: Update masterserver for current and previous version

- src/Lib/2D/Surface.hpp
- src/Lib/Util/Timer.hpp
- src/NetPanzer/Classes/Network/PowerUpNetMessage.hpp
Possible fix for
https://github.com/netpanzer/netpanzer/security/code-scanning/30 related to #104
For naming, I'm going by the Google style guide at https://google.github.io/styleguide/cppguide.html#Variable_Names which is mentioned in our contributing document.
> Fix some shadow declarations and CodeQL warning

- meson.build
- src/Lib/Util/FileSystem.cpp
> Fix crashing at main menu when sanitize is enabled

- README.md
> docs: Add WhatsApp and Instagram group

- .cirrus.yml
- .github/workflows/windows.yml
- meson_options.txt
- po/meson.build
> nls: Disable on Windows

- src/Lib/2D/CachedFontRenderer.cpp
@winrid I'm gonna reverse myself and suggest your way ;)
> maint: Narrow scope of cleanupThreshold

- src/NetPanzer/Views/Components/View.cpp
- src/NetPanzer/Views/Components/View.hpp
- src/NetPanzer/Views/GameViewGlobals.cpp
- src/NetPanzer/Views/GameViewGlobals.hpp
- src/NetPanzer/Views/MainMenu/MenuTemplateView.cpp
> Support Variable Width Text in Top Buttons

- .cirrus.yml
ChatGPT called me and suggested some changes to our Cirrus setup.
> CI: Refactor Cirrus

- src/NetPanzer/Classes/Network/NetMessageDecoder.cpp
- src/NetPanzer/Classes/Network/NetMessageEncoder.cpp
- src/NetPanzer/Classes/Network/NetworkClient.cpp
- src/NetPanzer/Classes/Network/NetworkClient.hpp
- src/NetPanzer/Classes/Network/NetworkServer.cpp
- src/NetPanzer/Classes/Network/NetworkServer.hpp
- src/NetPanzer/Network/ClientSocket.cpp
- src/NetPanzer/Network/ClientSocket.hpp
Fixes https://github.com/netpanzer/netpanzer/issues/189
@andy5995 have time to review?
> Fix Sanitizer Warnings in Netcode

- data/scripts/mainmenu.cfg
- data/scripts/mainmenu.lua
- src/Lib/2D/CachedFontRenderer.cpp
- src/Lib/2D/CachedFontRenderer.hpp
- src/Lib/2D/Color.cpp
- src/Lib/2D/Color.hpp
- src/Lib/2D/Surface.cpp
- src/NetPanzer/Interfaces/GameManager.cpp
- src/NetPanzer/Interfaces/GameManager.hpp
- src/NetPanzer/Interfaces/MenuConfig.cpp
- src/NetPanzer/Interfaces/MenuConfig.hpp
- src/NetPanzer/Interfaces/PlayerGameManager.cpp
- src/NetPanzer/Scripts/ScriptManager.cpp
- src/NetPanzer/Views/Components/newButton.hpp
- src/NetPanzer/Views/MainMenu/MenuTemplateView.cpp
- src/NetPanzer/meson.build
This PR provides an example of how to define a colour of an element in the mainmenu in a config file (lua script).
Further plan is to make the entire menu layout defined / customisable in a lua script. Does this idea sound appealing?
(Idea from @andy5995 and sounded like a good idea to me :).)
> Start defining properties for menu in lua script

- .github/workflows/appimage.yml
- .github/workflows/c-cpp.yml
- meson.build
- support/appimage/make-appimage.sh
> Set required versions for SDL2 and SDL2_ttf, add Ubuntu Focal test to CI

- src/Lib/Types/fXY.hpp
Fixes [https://github.com/netpanzer/netpanzer/security/code-scanning/36](https://github.com/netpanzer/netpanzer/security/code-scanning/36)
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert #36: Multiplication result converted to larger type

- src/NetPanzer/Classes/Network/NetMessageDecoder.cpp
- src/NetPanzer/Classes/Network/NetMessageEncoder.cpp
- src/NetPanzer/Network/ClientSocket.cpp
- src/NetPanzer/Network/ClientSocket.hpp
- src/NetPanzer/Units/UnitInterface.cpp
- src/NetPanzer/Units/Vehicle.cpp
- src/NetPanzer/Weapons/MissleWeapon.cpp
- src/NetPanzer/Weapons/ShellWeapon.cpp
- src/NetPanzer/Weapons/Weapon.cpp
Fixes https://github.com/netpanzer/netpanzer/issues/240
Some of the issues were introduce in https://github.com/netpanzer/netpanzer/pull/223/files
Others probably from UI refactor that removed surface initialization on the server side.
Tested w/ dedicated server, two dedicated bots, and a client.
Compiled server w/ sanitizer enabled, verified still don't get sanitizer warnings.
> Server Crash Fixes & Sanitizer Warnings

- .cirrus.yml
I believe this is all that's needed to fix the failing FreeBSD check
> CI: Bump FreeBSD to 14.1

- src/NetPanzer/System/SDLSound.cpp
In other words: fixes explosions always being at 100% volume.
Also adjusted the sound volume steps based on playing with a larger map.
> Fixing volume controls not affecting ambient sounds, explosions, etc.
